### ISSUE TITLE
[request] - change to MIT license

### ISSUE THREAD

**Issue by pajama** [loic-lopez/UMVC#42]
I would love to use this contribute to this framework, use it in my projects, and give proper attribution. 

Unfortunately, the GPL licensing requires us to completely open-source our work, which I'm unable to do due to other conflicting licenses.

Changing to an MIT license would allow us to incorporate UMVC.

Cheers!

**Comment by loic-lopez** [comment]
Hi, thanks for you interest to UMVC, I will change the licence to the MIT.

**Comment by loic-lopez** [comment]
@pajama as you can see the licence is now the MIT licence in the master branch.

**Comment by pajama** [comment]
This is great! Thanks so much for all the hard work, and for sharing it with us!

**Comment by loic-lopez** [comment]
@pajama Also you can post issues if you want to add some improvements!
